const KEY="levelup-web-state";let state=JSON.parse(localStorage.getItem(KEY)||"null")||{name:"Hunter",weight:105,target:80,phase:1,xp:320,quests:[false,false,false,false],weights:[],workouts:[],messages:[],tab:0,started:Date.now()};let sessionStart=Date.now();
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function login(){const n=document.getElementById("nameInput").value.trim()||"Hunter";state.name=n;save();document.getElementById("login").classList.add("hidden");document.getElementById("app").classList.remove("hidden");render()}
function logout(){document.getElementById("app").classList.add("hidden");document.getElementById("login").classList.remove("hidden")}
function showTab(t){state.tab=t;save();render()}
function pct(){return Math.max(0,Math.min(100,Math.round((state.xp%1000)/10)))}
function card(title,body,cls=""){return `<div class="card ${cls}">${title?`<div class="label">${title}</div>`:""}${body}</div>`}
function dashboard(){let done=state.quests.filter(Boolean).length;return `<div class="hero glow"><div class="eyebrow">SYSTEM ONLINE • WELCOME, ${state.name.toUpperCase()}</div><h2>LEVEL UP YOUR LIFE.</h2><div class="rank">RANK ${state.phase>=5?"S":"E"} HUNTER</div><p class="muted">Build strength. Complete quests. Unlock your next phase.</p><div class="progress"><i style="width:${pct()}%"></i></div><p class="note">${state.xp} XP • ${1000-state.xp%1000} XP to next level</p></div>
<div class="grid">${card("CURRENT WEIGHT",`<div class="stat">${state.weight} <small>kg</small></div>`)}${card("TARGET",`<div class="stat">${state.target} <small>kg</small></div>`)}${card("PHASE",`<div class="stat purple">${state.phase}</div>`)}${card("QUESTS",`<div class="stat green-t">${done}/4</div>`)}</div>
<h3 class="section-title">⚡ TODAY'S SYSTEM</h3><div class="grid"><div class="card"><b>Daily Momentum</b><p class="muted">Finish your quests and log a workout to earn XP.</p><button class="small-btn" onclick="showTab(1)">VIEW QUESTS</button></div><div class="card"><b>Quick Workout</b><p class="muted">Forge your body with today's training.</p><button class="small-btn" onclick="showTab(3)">OPEN FORGE</button></div></div>`}
function quests(){let qs=["Walk / cardio session","Drink enough water","Complete strength workout","Log today's progress"];return `<div class="hero"><div class="eyebrow">DAILY QUEST BOARD</div><h2>QUESTS</h2><p class="muted">Complete missions to earn XP and maintain momentum.</p></div><h3 class="section-title">Today's Quests</h3>${qs.map((q,i)=>`<div class="card quest ${state.quests[i]?"done":""}" style="margin:8px 0"><input type="checkbox" ${state.quests[i]?"checked":""} onchange="toggleQuest(${i})"><div><b>${q}</b><div class="note">+${i===2?150:100} XP</div></div></div>`).join("")}`}
function phase(){let lost=Math.max(0,105-state.weight),remaining=Math.max(0,state.weight-state.target);return `<div class="hero"><div class="eyebrow">TRANSFORMATION PROTOCOL</div><h2>PHASE ${state.phase}</h2><p class="muted">Track your weight and move toward your target.</p></div><div class="grid">${card("STARTING",`<div class="stat">105 kg</div>`)}${card("CURRENT",`<div class="stat">${state.weight} kg</div>`)}${card("TARGET",`<div class="stat gold">${state.target} kg</div>`)}</div><div class="card" style="margin-top:12px"><div class="row"><b>Progress to target</b><span class="pill">${Math.round((lost/(105-state.target))*100)}%</span></div><div class="progress"><i style="width:${Math.min(100,lost/(105-state.target)*100)}%"></i></div><p class="muted">${remaining.toFixed(1)} kg remaining</p><div class="form"><input id="weight" type="number" step=".1" placeholder="Weight (kg)"><input id="weightNote" placeholder="Note"><button class="primary" onclick="logWeight()">LOG WEIGHT</button></div></div><h3 class="section-title">Recent Logs</h3>${state.weights.slice(-5).reverse().map(x=>`<div class="card row" style="margin:7px 0"><b>${x.w} kg</b><span class="note">${x.d}</span></div>`).join("")}`}
function forge(){let ex=["Squats","Push-ups","Lunges","Plank","Dumbbell Row"];return `<div class="hero"><div class="eyebrow">TRAINING FACILITY</div><h2>FORGE</h2><p class="muted">Choose an exercise and record your training.</p></div><div class="grid">${ex.map((e,i)=>card(e,`<div class="row"><span class="pill">${i<2?"STRENGTH":"CORE"}</span><b>${i===3?"3 × 30s":"3 × 10"}</b></div><button class="small-btn" style="margin-top:12px" onclick="logWorkout('${e}')">COMPLETE</button>`)).join("")}</div><h3 class="section-title">Workout History</h3>${state.workouts.slice(-8).reverse().map(w=>`<div class="card row" style="margin:7px 0"><b>${w}</b><span class="green-t">+100 XP</span></div>`).join("")}`}
function oracle(){let msgs=state.messages.length?state.messages:[["AI","Greetings Hunter. I am your System Fitness AI Oracle. Ask a workout, nutrition or form question."]];return `<div class="hero"><div class="eyebrow">SYSTEM INTELLIGENCE</div><h2>✦ FITNESS ORACLE</h2><p class="muted">Instant guidance for workouts, nutrition and progression.</p></div><div class="bar" style="margin:12px 0">${["High protein meal ideas","Best fat-loss cardio","Fix squat knee cave"].map(x=>`<button class="small-btn" onclick="ask('${x}')">${x}</button>`).join("")}</div><div class="card">${msgs.map(m=>`<div class="message ${m[0]==="AI"?"ai":"user"}"><b>${m[0]}</b><br>${m[1]}</div>`).join("")}<div class="row" style="margin-top:12px"><input id="prompt" class="chat-input" placeholder="Ask the Oracle..." onkeydown="if(event.key==='Enter')sendAsk()"><button class="primary" style="width:auto" onclick="sendAsk()">SEND</button></div></div>`}
function badges(){let list=[["⚡","First Steps","Complete your first quest",state.xp>0],["♜","Iron Will","Complete 5 workouts",state.workouts.length>=5],["◉","Phase Hunter","Log your first weight",state.weights.length>0],["✦","Momentum","Complete all daily quests",state.quests.every(Boolean)],["♛","Level Master","Reach 1000 XP",state.xp>=1000],["🏆","Target Crusher","Reach target weight",state.weight<=state.target]];return `<div class="hero"><div class="eyebrow">ACHIEVEMENT VAULT</div><h2>BADGES</h2><p class="muted">Earn achievements by proving your consistency.</p></div><div class="badges" style="margin-top:12px">${list.map(b=>`<div class="card badge ${b[3]?"":"locked"}"><div class="symbol">${b[0]}</div><h3>${b[1]}</h3><div class="note">${b[2]}</div></div>`).join("")}</div>`}
function render(){document.querySelectorAll("[data-tab]").forEach(b=>b.classList.toggle("active",+b.dataset.tab===state.tab));let views=[dashboard,quests,phase,forge,oracle,badges];document.getElementById("content").innerHTML=views[state.tab]();save()}
function toggleQuest(i){state.quests[i]=!state.quests[i];state.xp+=state.quests[i]?100:-100;save();render()}
function logWeight(){let w=parseFloat(document.getElementById("weight").value);if(!w||w<20||w>300)return alert("Enter a valid weight.");state.weight=w;state.weights.push({w,d:new Date().toLocaleDateString(),n:document.getElementById("weightNote").value});state.xp+=50;save();render()}
function logWorkout(e){state.workouts.push(e+" • "+new Date().toLocaleDateString());state.xp+=100;save();render()}
function ask(x){document.getElementById("prompt").value=x;sendAsk()}
function sendAsk(){let p=document.getElementById("prompt").value.trim();if(!p)return;state.messages.push(["USER",p]);let a="Stay consistent: prioritize a sustainable calorie deficit, adequate protein, progressive training and recovery. For exercise form, use controlled reps and stop if you feel sharp pain. For personalized medical advice, consult a qualified professional.";if(/protein|meal/i.test(p))a="Budget-friendly protein options include eggs, dal, chickpeas, milk/curd and fish or chicken when available. Build each meal around a protein source plus vegetables and a sensible portion of carbs.";if(/cardio|fat loss/i.test(p))a="For fat loss, brisk walking, jogging and cycling are all effective. Start with a pace you can sustain, then gradually increase duration. Nutrition and overall activity matter more than one specific cardio exercise.";if(/squat|knee/i.test(p))a="Try reducing load and depth temporarily, keep the knee tracking roughly over the toes, maintain a stable foot tripod and control the descent. If pain persists, get your technique assessed.";state.messages.push(["AI",a]);save();render()}
setInterval(()=>{if(!document.getElementById("app").classList.contains("hidden")){let s=Math.floor((Date.now()-sessionStart)/1000),m=String(Math.floor(s/60)).padStart(2,"0"),q=String(s%60).padStart(2,"0");document.getElementById("timer").textContent=m+":"+q}},1000);
if(state.name&&state.name!=="Hunter"){document.getElementById("login").classList.add("hidden");document.getElementById("app").classList.remove("hidden");render()}
